<a href="https://colab.research.google.com/github/rb58853/ML-RSI-Images/blob/main/MyModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
from keras.preprocessing.text import Tokenizer
import numpy as np

class MyModel():
  def __init__(self, data_path, max_input_len = 500, max_item_output_len = 500, max_output_len = 500):
    self.max_item_output_len = max_item_output_len
    self.max_input_len = max_input_len
    self.max_output_len = max_output_len

    self.data:dict
    self.set_data(data_path)
    self.model = self.get_model

  def set_data(self,data_path):
    self.data = {
    'input':[
        'dog playing',
        'cat playing',
        'lion playing'
        ],
    'output':[
        ['dog playing', 'dog x'],
        ['cat playing',' cat x'],
        ['lion playing' , 'lion x']
        ],
    'types':
     [
        [4,6],
        [4,6],
        [4,6]
        ]
      }

  def get_train(self):
    # Crea un objeto Tokenizer
    tokenizer = Tokenizer()
    # Ajusta el tokenizer a tus datos
    types =  self.data['types']
    output = self.data ['output']
    input =  self.data ['input']

    tokenizer.fit_on_texts(input+['x'])
    vocab_size = len(tokenizer.word_index) + 1
    sequences_input = tokenizer.texts_to_sequences(input)

    sequences_output = []
    for item in output:
      texts = [text for text in item]
      sequences_output.append(tokenizer.texts_to_sequences(texts))

    train_x =  [np.array([date_input, date_type]) for date_input, date_type in zip(sequences_input, types)]
    train_x = np.array(train_x)
    train_y = np.array( [np.array(item) for item in sequences_output])

    return  {'train_x':train_x, 'train_y':train_y}

  def get_model(self):
    inputA = Input(shape=(2, max_input_len))
    x = Flatten(input_shape=(2, max_input_len))(inputA)
    x = Dense(32, activation='relu')(x)
    x = Dense(4, activation='relu')(x)
    x = Dense(4, activation='relu')(x)
    output = Reshape((max_output_len, max_item_output_len))(x)

# Convierte tus datos en secuencias de números


[[[2 1]
  [4 6]]

 [[3 1]
  [4 6]]

 [[4 1]
  [4 6]]]
[[[2 1]
  [2 5]]

 [[3 1]
  [3 5]]

 [[4 1]
  [4 5]]]


In [58]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Input, Dense, Reshape, Flatten
from keras.models import Model


max_input_len = 2
max_output_len = 2 #cantidad de salidas
max_item_output_len = 2 #cantidad de elementos en cada elemento de la salida
total_len_output = max_output_len * max_item_output_len



# Crear el modelo
model = Model(inputs=inputA, outputs=output)

# Compilar el modelo
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Entrenar el modelo
model.fit(train_x, train_y, epochs=10, batch_size=32)


Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: nan - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 18ms/step - loss: nan - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: nan - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: nan - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: nan - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: nan - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: nan - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: nan - accuracy: 0.5000
